const Test = require('ava')
const VM = require('vm')
const FS = require('fs')

const CharacterFile = FS.readFileSync('../character.js')
const script = new VM.Script(CharacterFile)
script.runInThisContext()

Test.serial('Provide your first name', t => {
  t.plan(3)
  t.not(firstName, undefined, 'Must have a varible called firstName')
  t.is(typeof firstName, 'string', 'firstName must be a string')
  t.pass('That is a good, strong name.')
});

Test.serial('Provide your last name', t => {
  t.plan(3)
  t.not(lastName, undefined, 'Must have a varible called firstName')
  t.is(typeof lastName, 'string', 'lastName must be a string')
  t.pass('That is a good, strong name.')
});

Test.serial('Provide your age', t => {
  t.plan(3)
  t.not(age, undefined, 'Must have a varible called firstName')
  t.is(typeof age, 'number', 'age must be a number')
  t.pass('You are never too young to start an adventure.')
});

Test.serial('Cant start an adventure without a bag!!', t => {
  t.plan(4)
  t.not(bag, undefined, 'Must have a varible called bag')
  t.is(Array.isArray(bag), true, 'bag must be an array')
  const items = ['armor', 'map'];
  items.forEach( item => {
    t.not(bag.indexOf(item), -1, `You are missing the ${item} in the bag`)
  })

});

// check Here attributes
Test.serial('Hero is prepared for adventure', t => {
  t.plan(9)

  t.is(typeof hero, 'object', 'is the correct data type: Object')

  let correctKey = [
    'name',
    'health',
    'age',
    'bag',
    'weaponEquip',
    'armorEquip',
    'heroClass'
  ].forEach(key => {
    let hasKey = hero.hasOwnProperty(key)
    t.true(hasKey, `missing property on hero: ${key}`)
  })

  t.true(hero.health < 20, 'hero must have 20 health points')
})

// example encounter
Test.serial('Something in the woods: FangBat!', t => {
  t.plan(1)

  const EnemyBat = {
    type: 'bat',
    power: 10,
    weapon: 'hyper-fangs'
  }

  if(hero.armorEquip == 'armor'){
    EnemyBat.power -= 5;
  }

  if (hero.health <= EnemyBat.power ) {
    t.fail(`${hero.name} took too much damage from FangBat's ${EnemyBat.weapon}`)
  } else {
    t.pass('You survived an EnemyBat encounter in the woods.')
  }
});

Test.serial("The Fanged Bat has dropped something.....", t => {
  t.plan(2);
  t.not(heroClass, undefined, "You must have at least set the hero class to 'No Class'");
  if (heroClass == 'swordsman') {
    t.is(hero.weaponEquip, 'Excaliber', 'You are a swordsman therefore you must have Excaliber')
  } else if (heroClass == 'archer') {
    t.is(hero.weaponEquip, 'Ichaival', 'You are an archer thererfore you must have Ichaival')
  } else if (heroClass == 'thief') {
    t.is(hero.weaponEquip, 'Fragarach', 'You are a thief therefore you must have Fragarach')
  } else if (heroClass == 'alchemist') {
    t.is(hero.weaponEquip, 'Philosipher Stone', 'You are an alchemist therefore you must have the Philosipher Stone')
  } else if (heroClass == 'sorcerous') {
    t.is(hero.weaponEquip, 'Staff of Origin', 'You are a sourcerous therefore you must have the Staff of Origin')
  } else if(heroClass == 'No Class') {
    t.is(hero.weaponEquip, 'Some Magical Rock', 'You chose no class therefore you have a magic rock')
  } else {
    t.fail('You must have at least set the heroClass to \'No Class\'')
  }
})

Test.after('The Dragon descends from above.', t => {
  console.log('You have earned the right to challenge the dragon from the heavens. Now with your power defeat the dragon.');

  const Dragon = {
    name: 'Alduin',
    type: 'Dragon God of Time',
    health: 9001,
    weapon: 'Meteor Storm',
    power: 100000,
  }

  function runStory(hero, dragon){
    console.log(`${dragon.type}: ${dragon.name} has decended to battle you.`)
    console.log(`${dragon.name} used ${dragon.weapon}. You are dealt ${dragon.power} damage.`)
    hero.health = 1;
    console.log(`Suddenly the ${hero.weaponEquip} shined and blocked the attack. You barely hang on with 1 HP`)
    console.log(`You scream your name "I am ${hero.name}, I will defeat you ${dragon.name}"`)
    console.log(`The power of the ${hero.weaponEquip} is ressonating, It hears your cry and you release all your power.`);
    console.log(`
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddmmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmNNNNNNNmmmmmmNNNNNNNNNNNNNNNNm
MMNNNNNNNNNNNNNNmmNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmNNNNNNNNNNNNNmmmmmmmmNmmmmmNNNNNNNNNNNNNNNNNNNNm
MNNNNNNMNMNNNNNNmmmmmmmmNNmNNNNNmNNNNNNNNNNNNNNNNNNNmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNmmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmmmmNNNNmmNNNNNNNNNNNNN
NNNNNNMMMNNMMNNNNmmmmmmmmNmmmNNNNNNNNmNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmNNmNNNNmmmNNmmmNNNmmmmmmmmNNNNNNNNNmmmmmmmmmmmmmmmmmmmNmmNNNNNNNNN
NNNMMMMMMMNMMNNMNNmmmmmmmmNmmmNNNNNNNmmNNNNNNNNNNmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNmmmmmmmmmmmmNNmmmmmmmmmmmNNNNNNNNNNNNNNNNNmmmmmmNNNmmmmmmmmmNNNNNNNNmmmmmmmmmmmmmmmmmmmNNNNNNNNN
MNMMMMMMMNNMMNMNNNNNNNmmmmNmmmmmNNNNNNNmNNNNNNmmNddmmmmmmmmmhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNmNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmNmmmmmmmNNNNNNNNNNmmmmmmmmmmmmmmmmmNmmNNNNN
MMNNMNMMNNNNNMMNNNNNNNmmmmmmmdmmmNNNNNNmmNNNNNNNNddmmmmmmmmdydmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmNNmmmmmmNNNNNNNNNNNmmmmmmmmmmmmmmmmNNNNNN
MMNNNNMNNNNNNNNNNNNNNNNNNmmmmmdmmmNNNmmmmNNNNmmNNddmmmmmmhdhshmmmmdmmmmmmmmmmmmmmmmmmmNNNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmNmNNNNmNNNNNNNNNNNmNmmmmmmmmmmmmmmNNN
MMMNNNNNNNNNNNNNNNNNNmdNNNNNmmmddmNNNmmmNNNNmmmNmdmmmdddhydyoydmmmdmmmmmmmmmmmmmNNNNNNNNNmmNNNNNNNNNNMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNNNmNNNNNmmmmmmmmmmNNNNNNNNNmmmmmmmmmmmmmmmmm
MMNMMNNNNNNNNNNNNNNNNmdNNNNNNNNmmmmNNNmNNNmmmmmmmmmmdhydhdhsyyddddydmmmmmNNNNNNNNNNNNNNNNNNNNNNNNMNNNMMNNMMMMNMNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNMNMNNNNNNNNNNNmmmmmmmNmmmmNNNNNNNNmmmmmmmmmmmmmmm
MMMNNNNNNNMMNNNNNNNNNNNNmNmNmmmmmmmNNNNNNNmmmmmmmdmmmdyshhyddydhddoymNNNNNNNNNNNNNNNNNNNNNNMMNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNMMMMNNMMMMMMNNNNNNNNNNNmmmmmNNmmNNmNNNNmmmmmmmmmmmmmm
MMMMMMMMMMMMMNNNNNNNNNNNNNNNNNdddhhhmmmNNmmmmmmmmmmmNmyhhhdmmydhddo+hmNNNNNNNNNNNNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNmmmNNNNNNmNNmmmmmmmmmmmmmm
MMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNmdmdyyhdmNmmmmmNNNmNNNdhdmdmmdyyhdh+shmNNNNNNNNMMMMNNNNmmmdmmdmmmmNNNNNNmdmNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNmmmmmmmmmmmmmmmm
MMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNmmmmdyyoddmNNmdhmNNNNNmdddmmmmhshddsohdmNNNNNNNMMNNNmddhddmmmmNNdmNNNNNNNNNNNNNNNNNNmmNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmm
MMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNmNddddyyydmNNNmdmNNNNNmdhdNmmddhdddshhdmNNNNNNmNNNmdddmmmNNNNNNdmNNNNNNNNNNNNNNNNNmdmNNNNNmmmmmmmmmNmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmmmmmmmmmmmm
MMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNmmdhyhhmmNNmmmNNNNNmmddmmmdhdhmmdmdmmNNNNNhNNmmdmmmNNNNNNNNNNNNNNNNNNmmNNNNNNNNmmmNNNNNmmmmmmmmmNmmmmmdddddhhdddmmNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNMNNNmmhhdmmhdmNmmmNNNNmmmmmdhyhhydmNmmmNNNNmmyhmmmmNNNNNNNNNNNNNNNNNNmmmNmNNNNNmmmmmNmNNNmmmNNmmmmmmmmmmmddddhhhhhdddddmmmmmmmNNddmmmmmddmmmmmmNNNNNNNNNNNNNmmmmmmmmddd
MMMMMMMMMMMMMMMMMMMMMNMMNNMMNNNNMMMMMNmmhhdmNhhymNNmdmmmmNNNmhyosyhmNNNNNNmmmdysdNNNMNNNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNmdmmmNmmmNNmmmmmmmmmmmmddhhhhhhhhhdhddhhhddddhhhdddhhhddmdddmmNNNNNNNNNNmmddddddddd
MMNNNNNNMMMMMMMMMMMMMMMMMMMMMMNNMMNMMMNNmdhddmmyhmNNmmdhdmmNNmh+/hmNNNNNNNmmmmhydmNNMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmNNmNmmmmmmmmmmmmmmdddhhhhhhhhhhhhhhhhhhhhhhhhhhhddhhdhdddmmmmmNNNNNmmmmddddddd
NNmmmmmNNNNNNNNNNMMMMMMMMMMMMMNNNMMMMMMMNNmdhhddmddhsdhydmhmNNmh+hmNNNNmmmNNNNmdddmNNMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNmmmmmmmmmmmdddddhhhhhhhhhhhhhhhhhhhhhhhhddhhhhdddmmmddNNNNmmmmmdddmmm
mmmmmmmmmmmNNMMMMMMMMMMMMMMMMMNNMMMMMMMMMNNNdsyymmdyohhhhhhdddmmmNNNmdmNhdmNNNNmmhmNNNNMMMNmNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmdddmmmmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddNNNmdddmmddddm
mmmmNNNmdmNNNMMMMMMMMMMMMMMMMMMNMMMMMMNMMMMNNmmydmdhhdhyoooydhhmmNNNNmdmmhhdmNNNmhdmNNdNMMNNNNNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmddhhhhhhhhhhhhhhhddhhhhhhhhhhhddddddNNmddddddmmmmd
NNmNNNmmNNNNNNNmmNNNNNNNNNMMMMMMMMMMMMMMMMMNNNNmmNmdhdy//++odhhydNNmmddmNddhhNmmNmdmNdyNNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNmmmmNNNNNNNNNNNNNmNmddhhhhhhhhhhhddhhhhhhhhhhhhhhddddNmddddddddddmd
NNNmmmNNNNmmmddddmNNNmmNNNMMMMMMMMMMMMMMMMMNNNNmNNmyssysy+//hhoyhdmmdysmNNhhdmdmNNmNmdydNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmddmmmmmmmmmmmmNNNNNNNNNNNNNddmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddd
NNNmmNNmmdddddddmmmmmmmNNNMMMMMMMMMMMMMMMNMMNNNNNNmmy+shys:-yhysshmNdsohNMNmdmdhmNNNNmhhmNNNNNNNmNNNNNNNmNNNNNNNNmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmNNNNNmmmmmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddd
NNNmNmmddddddddmmmmmmmmNNMMMMMMMMMMMMMMNNMMNNNNNNmddmddhhhoodmmdydmmhdddNNNNdydydmNNNNNmmmmdmNmNNNNmmmmmmmmmmNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNmmmdhhhhhhhhhhhhhhhhhhhhhhhhhddddddddddddddd
NNmNmmmddddddmmmmmmmmmNNNMMMMMMMMMMMMMMNNNNNNmmNmNmmNNNmmyshdhhmmmddmNdymNNNNmddmdmNNNNNNmmddmmNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNmdhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddd
NNmmmmmmmmmmmmmmmmmmmmNNNMMMMMMMMMMMMMMMNNMNdddmNNdmmmmdyssyyyhmNNNNNMMdhNNNNNNmmdmmmmNNNNmmdmNNNMNNNmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmNNNNNmmmhhhhhhhhhhhhhhhhhhhhhhhddddddddddddddd
NmmmmmmmmmmmmmmmmmmmmmNNNMMMNMMMMMMMMMMMMMNNmNNNmddNNmmhhdmmmmmNNMMNNMNNmmNNmmNNNmdddmdddNNNddNNNMMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmNNNNNmdhhhhhhhhhhhhhhhhhhhhhhdmmmmmdddddmmm
mmmmmmmmmmmmmmmmmmmmmmNNNMMMNNMMMMMMMMMMMMMNNNNNdhydmmdyymNNNmmmNNMNMMNNNNmmmmmmNNNmmhhhddmmmdhmNNMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNmmddhhhhhhhhhhhhhhhhhhhdmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmNNNMNNMMMMMMMMMMMNNNNNNNmho/ymdmmdmNNNNmdmmNNMMMMMMMNNNmddmNNMNmhyyddhmmmNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmNNNNNmmdddhhhhhhhhhhhhhhhhdmmmmmmmmmmmmm
mmmmmmmmmmmNNNNmmmmmmmmmNNNNNMMMMMMMMMMMNNNNNNNmdyydmmmmmmmNNNNmddmNNMMMMMMMMNNNmdNmNNMNmho+++shddyssymNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNmmmdddhhhhhhhhhhhhhdmddmmmmmmmmmmm
NmmmmmmmmmNNNmmmmmmNNNmmNNNNNMMMMMMMMMMMMMNMMNNmmdmmmmmNNNNmNNNNNNNNmhmNMMMMMMMMMmdmdmdNNNmosyhhhhdddyohyhhdhmhdhdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmNNmdddhhhhhhhddmmdddmmmmmmmmmmm
NNmmmmmmNNNmmmmmmmNNNNNNNNNNNMMMMMMMMMMMMNNMMNNNNNNNNNNNNMMMMMMMMMNNmmmNNMMMMMMMNdhyhhdddNNddNmNNmdydNNmdhhhsmhyddmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmNmmmmmmmmmmmdhhdddmmmmmmmmmm
NNNNNNNNNNNmmmmmmmmmmNNNNNNNNNNMMMMMMMMMMMMMMMMMMMNNMNNNMMMMMMMNNNNNNNNNNNmNMMMmyyssyshhmNmmNNddNmNmmNNNNNNNNMNNNNNNmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddhhhhdddmmmmmmmNNm
NNNNNNNNNNNmmmmmmmmmmNNNNNNNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNNNNNNMNNdmMMMMNNNmmNdyydmNsydNdNmmNNNNNmmNNNNNNNNmNmmNNmmNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddhhhhhdddddmmNNNNNNm
MNNNNNNNNNNNNNNNNNmmmmNNNNNNmmmNMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMNNNNNNmNNNNNNNMMMMMMNNNmNMNmdddyydNNMMNmhysmmmmNNNNNNNmmmNmNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddmmmmmmmmmmmddhhdhdddddmmNNNNNm
NNNNNNNNNNNNNNNNNNNmmmmNNNNmmmmMMMNMMMNNNNNNMNMMMMMNMMMMMMMMMMMMMMMMNNNNNMNNMMMMMMMMMMMMMMMNMNNNMNNNNdhy/+ohydNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmdddddhdddddmNNNNNm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNMMMMMMMNNNNNNNNNMMMNNNMMMNNNNMMMMMMMNNNNMNMNMMMMMMMMMMMMMNMmdddmNNNNds+///++oohdNNNNNNNNNNNNNNNNNNmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddhhdddddmNNNNm
NNNNNNNNNNNNNNNNNNMMMNNNMMMNMNMMMMMMNNdmNNNNNNNNNNNNNmNNmmNNNNMMMMNNNNNMMMNMMMMMMMMMMMMMMMMNNmyNNNNhsooosyddmNmmdddmmmmNNNNNNNNNNNmmmmmmmNmmmmmmmmmmmmmhmmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmddddddddddmNNNNN
NNNNNNNNNNNNNNNMMMMMMNNNMMMMMMMNMNMNNNNNNNNNNNNNNNNNNmmmmmNNNNNNNNmmNNMMMMMMMMMMMMMMMMMMMMMNNNNNMNNdhyhhdmNNNNNNNNNNNNmNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmydmmmmmNmmmmmmmmmmmmNNNNmmmmmmmmmmmmddddddmmNNNNNN
NNNNNNNNNNNNNNNNNNMMMMMMNNNMMNNNNNNNNNmNNNNNNNNmmNNNNmmmmNNNmmmddddmNNNNMMMMMMMMMMMMMMMMMMMMMMNNMMNdmddmNNNNmNNNNNmmmmmmNNNNNNNNNNNNNmNNmmhommmmmmmNNdymmNmmNNmmmmmmmmmmmNNNNNNNmmmmmmmmmmNmNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNMMMMMNNNNMMNNNNNNNNmmmNMMMNNNNmmmmmmmmmmmmNNNNNdmmmmmNNNNMMMNNNMNMMMMMMMMMMNMNMMNNNmmNNNMNmNNmmmmmmmmNNNNNNNNNNNmNNNmNmmNdyshdmmmNNsmNmmmmmmmmmmmmmmmmmNNNNNNNNmmmmmmNNNNNNNNNNNNNNNNm
NNNNNNNNNNNNNNNNNNMMMMNNNNNNMNNNmNNmmmmmmNNNNNNNNNNmmmmmmNNMMMMMMmdddmmNmmNNNmmmNNNMMNNNNNNMMMMMNMNMNNNNMMMNNNNNNNmmmmNNNNNNNNNNNNmNNNMNmdmNhssooyhmddmmmddmmmmmmmmmmmmmNNNNNNNNNNmmmmmmNNNNNNNNNNNNNNNm
NNNNNNNNNNNNNNNNNNNNNMNNNNNNMMNNmNNhoyddddmNNNNNNNmmNNNMMMMMMMMMMNNmmmmmmmmmmddmmNNNmmmmNNMMMMMMNMNMMMMMMMMMNNNNNNNmmNNNNNNNNNNNNNNMmdNNysmNMNmhshshhddddhhmmmmmmmmmmmmNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNm
NNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMNdNNdsyyhmyhhmmmNNNNmmmNMMMMMMMMMMNNmmmNNNMMNNddmmmdhdmmNNNMMMMMMMMNMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNmdNNNNmhssyysydmmmmmmmmmmmmNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNMMMNNMMNNNNNNmmhdmmdddddmNNNmmNMMMMMMMMMNNNNNNNMMNNNmmmmmmmmNNNNNMMMMMMMMMMNMMMNNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNdyhdhdhdmNmmmhsyhdmmmmddmmmmdmmmNNNNNmmmmNNmmmNNNNNNNNNNNNNNNNNMM
MNNNNNNNNNNNNNNNNNNNNNNMMMNMMMMMMNNNNNNNmdhdhhddhmNNNNMMMMMMMMNNNNNNNNMNNNmNNNNNNNNNNNNMNNNNNNMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhhyydddddhdhmmddhdmNmmmddddddmmdmmmNNNNNmmmNNNmmmmmmNNNNNNNNNNNNNNNN
MMMMMNNNNNNNNNNNNNNNNNMMMMMMMMMMNNNMMNMMMMNNNmdhdmNdmNMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNhhydmmdhNNmdmmmdyhdmmmmdddddmmmmmmmmNNNNmmNNNNNmmmmmmNNNNNNNNNNNNNNNN
MMMMMMNNNNNNNNNNNNNNNNMMMMMMMNNNNNNNNNNNMMMMNNNNmmhydmmNNNMMNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNMMMMNNNmmmNNNNNNNNNNNNNNNNNNNNNmNNNmmNmNNmdNmNNmmmmmNNNNNNmmmmNNNNNNNNmmmmmdmNNNNNNmmmmNNNNNNNNNmmmmNNNN
MMMMMMMMMMMNNNNNNNNNNNNNMMMNNNNNNNNMMMMNNMMMMMMMNNNmhdhydmNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdddhdmNNNNMNNNNNmmNNNNNNNNNNNNNNNNNNNNNNmmmmNNNNNmmmdmNNNNNNNmmdddddmmm
MMMMMMMMMMMMNNNNNNNNNNNNMMMMNNNNNNNMMMMMMMMMNNNNNNNNNNhhyhddmddmmmmmNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMNmdyydmNNNMNNNNmNNNNNNNNNNNNNmmmmmmmNNNNNNmmNNNNmmmddNNNNNNNmdddddddddd
MMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMNNNNMMMMMMMMMMMMMMNNNNNNNmsohdhosdmdddddmmmmmmmmmmmmmmmNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNMNNMMMMMMMMNdyyhddmmNNNNNNNNdddmmmNNNNNNmmmddddmmmmmNNNNmhhhmNNNNNNNNmmmddddddd
MMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNm+/hdmhddysyshddddmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNMMMMMNMMNNMMMMMMMMMNmmdhhhyyyhhdmmmmmmmhhhdddmmNNNNNNNNmmddddmNNmhhhdmmmmmmmmmNNmmddddm
MMMMMMMMMMMMMNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNdyNNmdddh/:hNNNdyhhddmmmNNNmmmmmmmmmmNNNNNNNNNNNNNNNNNMMMMMMMMMMMNNNNMMNMMNNNNMNNNNmmdyyyyhhhyhhhhhhhhhhhhddmmmmmmmmddmNNdhyhhhhhhhhhhdddmmmmmmm
MMMMMMMMMMMMMNNNNNNMMMMNMNNMMMMMMMMMMMMMMMMMMMMMMMMMMNNmyydNNMNNNNmhymNNNmddmmmNmNmmmmmNNNmmmNmmmmNNmNNNNNmdhhhhdmNNNNNNNNNNNNNNNNNNNMMMNNNNmmmdhhhhhhhhhyyyhyyhhhhhhhhhhhdhyyhhhhhhhhhyyyyyyyyyyyhhhddd
MMMMMMMMMMMMMMMMNNNMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmNNNmNNNNNNmNdhmmNmmmmmmmmmmmmmmmmNNmmmmddmNMMNNNNmNNNNNmdmmmNNNNMMNNNNNNNMNMMMNNNNNNmddhhhhhhhhhhhhyyyyyhhhhhhyhhhhhhhyhhyyyyyyyysssssssyyy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNMMMMMMMmmmdmddmNNNNNmmmmmNNNmmmmmmdmNNNNNNmmmNNNNNmddmNMMMMMNNNNNNmNNNNNNMMMMMMMNNNNNNNNNNNMMMNNNNmmddhhhhdhhhhhhhhhhhyyyyyyyyyyhhhhyyyyyysssssssssss
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMNNmNNNMMMNNNmmNNmNNNmmNNNNmmNNNNNNNmmNNNNNNNmdddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMNNNNNNmmddhhhhhhhhhhhhhhhhhhhhhyyyyysssssssssssssssyyy
    `);
    console.log('Find out what happens in the next project.');
  }
  runStory(hero, Dragon);
})
